import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Header from '../components/Header'
import Footer from '@/components/Footer'
import styles from '../styles/Home.module.css'
import { getPosts } from '@/services'

export default function Home({posts}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Header posts={posts} />
        <Footer />
      </main>
    </>
  )
}

export async function getStaticProps(){
  const posts = await getPosts(); 

  return {
    props: {posts}
  }
}